### ISSUE TITLE
Feat: Implement Push Notifications Support

### ISSUE THREAD

**Issue by abhishek310001** [jalantechnologies/react-native-template#51]
## Description
Integrate support for push notifications, allowing users to receive real-time alerts, updates, or messages from the app. This includes setting up Firebase Cloud Messaging (FCM) for both iOS and Android platforms, following the established patterns in the codebase.

### Architecture Overview
The push notification system will follow the existing codebase patterns:
- **Service Layer:** Create `NotificationService` extending the `APIService` pattern
- **Context:** Create `NotificationContext` following `AuthContext`/`AccountContext` patterns
- **Configuration:** Use `react-native-config` for Firebase configuration

### Dependencies on Backend
- Requires **flask-react-template#511** (Device Management API) to be completed first
- Backend endpoints needed:
  - `POST /api/accounts/:accountId/devices` - Register device token
  - `DELETE /api/accounts/:accountId/devices/:deviceTokenId` - Unregister device token

### Phase 1: Firebase Setup & Configuration
- [ ] Install Firebase dependencies:
  - `@react-native-firebase/app`
  - `@react-native-firebase/messaging`
- [ ] Create `google-services.json` placeholder for Android (`/android/app/`)
- [ ] Create `GoogleService-Info.plist` placeholder for iOS (`/ios/`)
- [ ] Update `app.json` for Firebase configuration
- [ ] Add Firebase environment variables to `.env.example`:
  ```
  FIREBASE_PROJECT_ID=
  FIREBASE_APP_ID_ANDROID=
  FIREBASE_APP_ID_IOS=
  ```
- [ ] Update iOS `AppDelegate.mm` for Firebase initialization
- [ ] Update Android `MainApplication.kt` for Firebase initialization
- [ ] Configure iOS APNs capability in Xcode project

### Phase 2: Notification Service
- [ ] Create `/src/services/notification.service.ts`:
  ```typescript
  class NotificationService {
    static async requestPermission(): Promise<boolean>
    static async getDeviceToken(): Promise<string>
    static async registerDeviceToken(accountId: string, token: string): Promise<void>
    static async unregisterDeviceToken(accountId: string, tokenId: string): Promise<void>
    static async onTokenRefresh(callback: (token: string) => void): Unsubscribe
  }
  ```
- [ ] Add notification types to `/src/types/notification.ts`:
  ```typescript
  interface DeviceToken {
    id: string;
    token: string;
    platform: 'ios' | 'android';
    active: boolean;
  }
  
  interface PushNotification {
    title: string;
    body: string;
    data?: Record<string, string>;
  }
  ```
- [ ] Export from `/src/services/index.ts`

### Phase 3: Notification Context
- [ ] Create `/src/contexts/notification-context.tsx`:
  ```typescript
  interface NotificationContextInterface {
    hasPermission: boolean;
    isLoading: boolean;
    requestPermission: () => Promise<boolean>;
    deviceToken: string | null;
    lastNotification: PushNotification | null;
  }
  ```
- [ ] Handle foreground notifications (display in-app)
- [ ] Handle background notifications (when app is in background)
- [ ] Handle notification tap actions (deep linking ready)
- [ ] Export from `/src/contexts/index.ts`

### Phase 4: Integration with Auth Flow
- [ ] Modify `/src/contexts/auth-context.tsx`:
  - Register device token on successful login/OTP verification
  - Unregister device token on logout
- [ ] Update `/src/navigators/application.tsx`:
  - Add `NotificationContextProvider` to provider hierarchy
  - Initialize notification listeners on app start
- [ ] Modify `/src/screens/startup/startup.tsx`:
  - Request notification permission during startup (optional prompt)

### Phase 5: Notification Settings UI
- [ ] Create `/src/screens/profile/notification-settings.tsx`:
  - Toggle push notifications on/off
  - Display current permission status
  - Link to system settings if permission denied
- [ ] Add navigation entry in `/src/navigators/profile.tsx`
- [ ] Add settings option in profile screen

### Phase 6: In-App Notification Display
- [ ] Create `/src/components/notification-banner.tsx`:
  - Toast-style notification for foreground notifications
  - Configurable duration and styling
  - Tap to dismiss or navigate
- [ ] Integrate with theme from `app-theme.ts`

### Phase 7: Documentation & Configuration Guide
- [ ] Update `README.md` with push notification setup instructions
- [ ] Create `docs/PUSH_NOTIFICATIONS.md` with:
  - Firebase project setup steps
  - iOS APNs certificate configuration
  - Android FCM setup
  - Environment variable configuration
  - Testing push notifications guide

## Acceptance Criteria
- [ ] Push notification service (FCM) integrated for both iOS and Android
- [ ] Ability to receive notifications in foreground, background, and killed states
- [ ] Device token automatically registered on login
- [ ] Device token automatically unregistered on logout
- [ ] Notifications configurable (can be disabled by user)
- [ ] In-app notification display for foreground scenarios
- [ ] Clear documentation for client project configuration
- [ ] Works with existing Datadog monitoring integration

## Configuration for Client Projects
When forking this template for a new project, developers need to:
1. Create a Firebase project
2. Add iOS and Android apps to Firebase
3. Download and replace `google-services.json` and `GoogleService-Info.plist`
4. Configure iOS APNs in Apple Developer Portal
5. Upload APNs certificate to Firebase Console
6. Set environment variables

## Testing Guide
- [ ] Unit tests for NotificationService
- [ ] Integration tests for token registration flow
- [ ] Manual testing checklist:
  - iOS foreground notification
  - iOS background notification
  - iOS killed state notification
  - Android foreground notification
  - Android background notification
  - Android killed state notification
  - Token refresh handling
  - Logout token cleanup

## Dependencies
- Backend: [flask-react-template#511](https://github.com/jalantechnologies/flask-react-template/issues/511) - Device Management API
- Backend: [flask-react-template#512](https://github.com/jalantechnologies/flask-react-template/issues/512) - Push Notification System

## References
- [React Native Firebase Messaging](https://rnfirebase.io/messaging/usage)
- [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging)
- [APNs Setup Guide](https://firebase.google.com/docs/cloud-messaging/ios/certs)
